### ISSUE TITLE
over 15min voice call

### ISSUE THREAD

**Issue by kwangjaeyoo** [zhanglihow/SipVoice#1]
15 minutes after starting the call,

There is no sound.

using other lib will just hang up,

pjsip is not cut off and there is no sound.

**Comment by zhanglihow** [comment]
> 15 minutes after starting the call,
> 
> There is no sound.
> 
> using other lib will just hang up,
> 
> pjsip is not cut off and there is no sound.
Can you first determine if it is a server issue

**Comment by zhanglihow** [comment]
> 15 minutes after starting the call,
> 
> There is no sound.
> 
> using other lib will just hang up,
> 
> pjsip is not cut off and there is no sound.


Can you first determine if it is a server issue

**Comment by kwangjaeyoo** [comment]
It seems to be a problem with my server.

sip lib works fine.

Thank you.
