### ISSUE TITLE
两个安卓手机 通话没有声音

### ISSUE THREAD

**Issue by xcfdszzr** [zhanglihow/SipVoice#3]
在你的demo里面 我发现一个问题，手机能与window系统通话，但是两个手机之间通话是没有声音的。
希望作者能给一个完整的demo提供大家思考。
如果后面能把视频通话发出来那么更是好了。
谢谢作者

**Comment by zhanglihow** [comment]
这就是完整的demo，我用手机是没问题的。
不知道是不是有服务器的问题，你可以用miniSipServer 测试下
