### ISSUE TITLE
无法录音

### ISSUE THREAD

**Issue by pkxutao** [zhanglihow/SipVoice#4]
您好，引入了您的项目发现非常好用，完成度非常高，但有个录音功能未实现，我自己也研究了好久，发现网上的资料非常少，请问您的资料是哪里找的呢？pjsip是提供录音的，但没有接口文档来指引自己研究非常困难，麻烦给指条明路，谢谢

**Comment by zhanglihow** [comment]
主要是靠研究 sip 文档，和我集成的这个sip库已实现的方法来看的，可以看下 pjsua2JNI，SipService，录音这个只要拿到通话的流就好了。

**Comment by pkxutao** [comment]
我看了其实是有AudioMediaRecorder这个类的，但怎样使用有点抓瞎。。。

**Comment by zhanglihow** [comment]
试试这个：https://www.cnblogs.com/mobilecard/p/6722162.html

**Comment by zhanglihow** [comment]
具体可以看看源码：https://github.com/pjsip/pjproject/blob/master/pjsip/src/pjsua2/media.cpp
上面那个方法可以参照：SipCall.setMute()

**Comment by pkxutao** [comment]
> 具体可以看看源码：https://github.com/pjsip/pjproject/blob/master/pjsip/src/pjsua2/media.cpp
> 上面那个方法可以参照：SipCall.setMute()

非常感谢您给的资料，已经实现了录音，还有个问题，现在服务器是使用rc4加密的，请问这个在哪里设置呢？也是查了很多资料没查到设置加密方式的地方，谢谢

**Comment by zhanglihow** [comment]
这个就不清楚了
